version: "3"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: runcheck_dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - runcheck

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: runcheck_dynamodb_admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local
    networks:
      - runcheck

volumes:
  dynamodb-data:

networks:
  runcheck:
