version: "3"

services:
  # Legacy Laravel PHP backend
  # php:
  #   container_name: runcheck_php
  #   build: ./php
  #   volumes:
  #     - ../backend:/var/www/html
  #     - ./php/php.ini:/usr/local/etc/php/php.ini
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - runcheck

  # Legacy MySQL
  # db:
  #   image: mysql:5.7
  #   container_name: runcheck_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: "Asia/Tokyo"
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - ./db/data:/var/lib/mysql
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #     - 53306:3306
  #   networks:
  #     - runcheck

networks:
  runcheck:
